// Generated by scripts/build-reviewed-address-uses.mjs; do not edit.
import type { ReviewedAddressUse } from '../lib/reviewedAddressUses'

export const reviewedAddressUses: ReviewedAddressUse[] = [
  {
    "featureId": "landmark-vs-site-12",
    "expectedSourceRecordIds": [
      12
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          12
        ],
        "mode": "address-reference",
        "use": "黄浦区业余大学四川南路校区；成人／社区教育",
        "address": "四川南路35号",
        "note": "现代教育用途有采购门址记录；尚未逐栋核实与晓明女校的建筑延续。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "hp-college",
            "title": "黄浦区业余大学：政府采购校址清单",
            "url": "https://jpg.zfcg.sh.gov.cn/sh-gov-open-doc/1046AF/sh/protocolExport/58a9476a-e0da-4664-991f-8cb39b3be5d0.pdf",
            "informationAsOf": null,
            "accessedOn": "2026-09-24",
            "supports": "采购清单将上海市黄浦区业余大学列于四川南路35号。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-15",
    "expectedSourceRecordIds": [
      15
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          15
        ],
        "mode": "address-reference",
        "use": "黄浦区业余大学四川南路校区；成人／社区教育",
        "address": "四川南路37号",
        "note": "同号校址明确；不能把整个现代校区直接等同圣母院孤儿院某一楼。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "hp-college-37",
            "title": "黄浦教育网络采购清单",
            "url": "https://jpg.zfcg.sh.gov.cn/sh-gov-open-doc/1108QZ/13b07c4e-f985-4fb5-bd14-31d9d0731fe5.pdf",
            "informationAsOf": null,
            "accessedOn": "2026-09-24",
            "supports": "列出黄浦区业余大学四川南路校区，门址37号。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-32",
    "expectedSourceRecordIds": [
      32
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          32
        ],
        "mode": "current-use",
        "use": "上海基督教青年会；社会服务机构",
        "address": "西藏南路123号",
        "note": "已查到同址同名机构；本轮仅填该机构用途，不断言整栋楼只作办公或各楼层功能。",
        "identityBasis": "同号同名上海基督教青年会机构用途；不宣称逐栋原楼存续。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "ymca",
            "title": "上海市民宗局：上海基督教青年会",
            "url": "https://mzzj.sh.gov.cn/2021jdj_shjdjqnh/index.html",
            "informationAsOf": null,
            "accessedOn": "2026-09-24",
            "supports": "青年会介绍及联系门址西藏南路123号，支持社会服务机构用途。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-132",
    "expectedSourceRecordIds": [
      132
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          132
        ],
        "mode": "address-reference",
        "use": "淡水公寓，住宅小区",
        "address": "淡水路361号",
        "note": "乐居与房天下均列同一小区及门址，支持现代住宅用途；平台未标资料更新时间，不用其建成年份证明法国援助俄侨机构旧楼存续，旧今地块边界待核。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "fc2-danshui-leju",
            "title": "乐居：淡水公寓基本信息",
            "url": "https://house.leju.com/sh/744/xinxi/",
            "informationAsOf": null,
            "accessedOn": "2026-09-28",
            "supports": "明确淡水路361号为淡水公寓，物业类型住宅；平台未给资料更新时间，不采信建造年份为历史原楼存续证据。"
          },
          {
            "id": "fc2-danshui-fang",
            "title": "房天下：淡水公寓小区信息",
            "url": "https://www.fang.com/xiaoqu/sh-1210000743/",
            "informationAsOf": null,
            "accessedOn": "2026-09-28",
            "supports": "小区地址黄浦区淡水路361号，并有住宅户型及二手房信息；只交叉支持现代小区与门址，不证明俄侨救济机构旧建筑仍在。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-136",
    "expectedSourceRecordIds": [
      136
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          136
        ],
        "mode": "address-reference",
        "use": "黄浦区卫生事务管理中心；公共卫生事务办公",
        "address": "合肥路360号",
        "note": "2025年采购人门址证据；旧防疫机构与现办公楼的沿革、楼栋未核实。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "hp-health",
            "title": "2025年黄浦区卫生事务管理中心采购文件",
            "url": "https://sh-gov-open-doc.oss-cn-shanghai.aliyuncs.com/1108QZ/5cf0d1d4-1eed-41a3-8050-d781a7a88b6b.pdf",
            "informationAsOf": "2025-04",
            "accessedOn": "2026-09-24",
            "supports": "采购人上海市黄浦区卫生事务管理中心，地址合肥路360号。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-137",
    "expectedSourceRecordIds": [
      137
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          137
        ],
        "mode": "address-reference",
        "use": "黄浦区血液管理中心所列办公地址之一（304室）",
        "address": "黄陂南路630号304室",
        "note": "证据仅覆盖304室，不能外推整栋仍为医院；另列制造局路181号，保留多办公地点。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "hp-blood",
            "title": "上海市血液管理办公室：机构一览",
            "url": "https://www.shblood.org.cn/organization/list.html",
            "informationAsOf": null,
            "accessedOn": "2026-09-28",
            "supports": "黄浦区血液管理中心列有制造局路181号及黄陂南路630号304室；只支持所列房间的机构用途。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-142",
    "expectedSourceRecordIds": [
      142
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          142
        ],
        "mode": "address-reference",
        "use": "淮海中路街道社区卫生服务中心；社区医疗",
        "address": "淡水路285号",
        "note": "2026年采购公告确认现代机构；尚未证明与旧小学及幼稚园建筑相同。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "danshui-clinic",
            "title": "2026年淮海中路街道社区卫生服务中心采购公告",
            "url": "https://www.ccgp.gov.cn/cggg/dfgg/zbgg/202606/t20260625_26811070.htm",
            "informationAsOf": "2026-06-25",
            "accessedOn": "2026-09-28",
            "supports": "采购单位全名及地址淡水路285号。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-144",
    "expectedSourceRecordIds": [
      144
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          144
        ],
        "mode": "address-reference",
        "use": "SOHO复兴广场办公楼，含金佰利商用区域办事处",
        "address": "淡水路299号SOHO复兴广场A栋12楼",
        "note": "企业官网联系页直接列此办公门址；只确认现代楼宇和所列办公室，不证明东南高职旧校舍保留。页面未标更新日；其他公司的注册地址与实际办公地址不能混用。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "fc2-danshui-office",
            "title": "金佰利商用官网：联系我们",
            "url": "https://www.kcprofessional.com.cn/zh-cn/contact-us",
            "informationAsOf": null,
            "accessedOn": "2026-09-28",
            "supports": "区域办事处明确为淡水路299号SOHO复兴广场A栋12楼，支持现代办公用途；页面无更新时间，不推定东南高职校舍保留。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-147",
    "expectedSourceRecordIds": [
      147
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          147
        ],
        "mode": "address-reference",
        "use": "思南新天地幼儿园，学前教育",
        "address": "合肥路406号",
        "note": "2026年官方招生信息提供同号幼儿园门址，支持现址教育用途；是否沿用棉布公所原建筑及院落范围仍须沿革或地籍证据。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "fc2-hefei-kindergarten",
            "title": "上海市政府：2026年黄浦区幼儿园招生入园工作实施意见",
            "url": "https://www.shanghai.gov.cn/hpqxqjy/20260420/32fe4193d679456f94194479ba4372a4.html",
            "informationAsOf": "2026-04-15",
            "accessedOn": "2026-09-28",
            "supports": "2026年招生信息将思南新天地幼儿园列于合肥路406号，支持在用幼儿园门址；不证明原棉布公所整栋存续或同一地块边界。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-184",
    "expectedSourceRecordIds": [
      184
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          184
        ],
        "mode": "address-reference",
        "use": "黄浦区行政服务中心／企业登记许可等政务服务",
        "address": "巨鹿路139号",
        "note": "官方现行联系页可证同号政务服务用途；不因此认定原同义小学建筑仍存或中心占用与小学完全一致的地块。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc3-julu-services",
            "title": "上海市市场监督管理局：联系我们",
            "url": "https://fw.scjgj.sh.gov.cn/shaic/index/lxwm.jsp",
            "informationAsOf": null,
            "accessedOn": "2026-09-29",
            "supports": "官方现行联系页将黄浦区企业登记许可窗口列于巨鹿路139号行政服务中心；仅支持现代政务服务门址。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-194",
    "expectedSourceRecordIds": [
      194
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          194
        ],
        "mode": "address-reference",
        "use": "上海中华职业教育社社址／团体办公",
        "address": "雁荡路80号",
        "note": "机构官网明确同号联系地址；现代职教社办公不等于第一中华职业补习学校仍在办学，也不因POI称旧址就写成开放纪念馆。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc3-vocational",
            "title": "上海中华职业教育社官网：联系地址",
            "url": "https://www.shzhzjs.cn/m_include/db.html",
            "informationAsOf": null,
            "accessedOn": "2026-09-29",
            "supports": "官方网站页脚列社址雁荡路80号，支持职教团体办公门址；不证明旧第一补习学校今日仍在办学或对公众开放。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-french-park",
    "expectedSourceRecordIds": [
      196
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          196
        ],
        "mode": "current-use",
        "use": "复兴公园：公共公园及临街开放绿地",
        "address": "重庆南路与复兴中路交会处／复兴公园",
        "note": "公园名与路口检索对上，2023、2025官方报道支持現公园和开放绿地用途；仅确认园区级功能，不把路口参考点当成历史园界或入口测绘。",
        "identityBasis": "Koukaza／French Park与复兴公园名称及公园用途对应；只确认园区级功能。",
        "reviewedOn": "2026-09-30",
        "sources": [
          {
            "id": "fc7-fuxing-park",
            "title": "上海市民政局：沿绿脉赏苏河，入口袋享绿意",
            "url": "https://mzj.sh.gov.cn/lnb-xw/20230130/8357d32a9c0647c288175acb9dc78faa.html",
            "informationAsOf": "2023-01-30",
            "accessedOn": "2026-09-30",
            "supports": "官方检索正文确认复兴公园重庆南路、复兴中路围墙拆除透绿；原页复取失败。支持路口公园现状，不作为历史边界测绘。"
          },
          {
            "id": "fc7-fuxing-park2025",
            "title": "上海市城管执法局：跨街道联合治理",
            "url": "https://cgzf.sh.gov.cn/channel_8/20250319/e1207b8474cd48b1a283469c6d30da98.html",
            "informationAsOf": "2025-03-19",
            "accessedOn": "2026-09-30",
            "supports": "官方报道明确复兴公园重庆南路路口及重庆南路—复兴中路路口治理，支持现公共公园／周边步行空间用途。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-208",
    "expectedSourceRecordIds": [
      208
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          208
        ],
        "mode": "address-reference",
        "use": "上海交通大学医学院附属瑞金医院卢湾分院；医疗",
        "address": "重庆南路149号",
        "note": "现代医院门址清楚；仁爱会总院与现代院区的具体建筑延续待核。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "ruijin-luwan",
            "title": "高德：瑞金医院卢湾分院",
            "url": "https://www.amap.com/place/B00155KIBR",
            "informationAsOf": null,
            "accessedOn": "2026-09-24",
            "supports": "医院名称及重庆南路149号。只采现代门址用途，不取坐标。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-225",
    "expectedSourceRecordIds": [
      225,
      1512
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          225,
          1512
        ],
        "mode": "address-reference",
        "use": "新电大厦／上海电力设计院有限公司办公",
        "address": "重庆南路310号",
        "note": "2025年企业招聘通过高校官网公开公司地址及新电大厦名。VS225与1512两条法电厂历史记录仅共享同号现址证据，原工厂边界、拆建、遗存仍未确证；不同域名的博彩套壳网页排除。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc3-sepd",
            "title": "广州城市理工学院就业网：上海电力设计院招聘",
            "url": "https://jyw.gcu.edu.cn/2025/0227/c2427a182078/page.htm",
            "informationAsOf": "2025-02-27",
            "accessedOn": "2026-09-29",
            "supports": "企业招聘正文列公司地址上海市黄浦区重庆南路310号新电大厦，支持工程设计企业办公。非同址法电厂的建筑存续证明。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-232",
    "expectedSourceRecordIds": [
      232,
      233,
      234
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          232,
          233,
          234
        ],
        "mode": "address-reference",
        "use": "黄浦区人民检察院；司法机构办公",
        "address": "建国中路22号",
        "note": "只支持今院落门址。中央巡捕房、女监、法院各自的历史用途和范围保留，未把三条历史记录合成同一栋楼。",
        "retainedHold": {
          "reason": "已核实际分片research/unresolved-landmarks/010-b.json，按ID定位。建议改为unresolved/no，现代地点仅留在notes的空间参照；保留历史身份增量，不把附近用途填作原址用途。 执行hold时只撤本研究批准形成的现代用途override/采用结果；保留历史feature、原名、历史沿革、XY及其他经独立批准的来源，不将null写成一条有效override。 同址组成员：232,233,234；root须逐成员追踪独立证据，不能据本patch改写组外研究或抹去其他批准。",
          "reviewRef": "research/corrections/2026-09-18-001-010/README.md"
        },
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "procuratorate",
            "title": "黄浦区人民检察院官网",
            "url": "https://www.sh.jcy.gov.cn/hpjcy/lzqk/jcqb/index_8.jhtml",
            "informationAsOf": null,
            "accessedOn": "2026-09-28",
            "supports": "官网页脚列黄浦区人民检察院，建国中路22号。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-236",
    "expectedSourceRecordIds": [
      236,
      237
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          236,
          237
        ],
        "mode": "address-reference",
        "use": "黄浦区人民检察院司法办案及办公院区",
        "address": "建国中路28号",
        "note": "采购清单精确列28号，承建方说明司法办公用途。保护修缮楼址另为20、22号，不能把旧驻车间和财务处都认成该保护建筑本体；两条历史记录仍分列，同号用途有据而非逐楼存续核定。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc3-procurator-project",
            "title": "永业集团：黄浦区检察院保护修缮项目",
            "url": "https://www.yongye.com.cn/mobile_yongye/jtyw_lsjz.html",
            "informationAsOf": "2014年9月完工（网页未标更新日）",
            "accessedOn": "2026-09-29",
            "supports": "说明建国中路20、22号旧建筑改为司法办案办公空间，项目地址另列28号；支持院区用途，不能将旧车务处、财务处与指定保护楼栋自动等同。"
          },
          {
            "id": "fc3-procurator-list",
            "title": "上海政府采购：2024年打印机框架协议采购单位清单，第16页",
            "url": "https://jpg.zfcg.sh.gov.cn/sh-gov-open-doc/1046AF/sh/protocolExport/923f036e-8fe3-4beb-8f6c-22531fbc6461.pdf",
            "informationAsOf": "2024年采购项目",
            "accessedOn": "2026-09-29",
            "supports": "PDF第16页经文本及整页图像核验，黄浦区人民检察院对应建国中路28号；搜索的近期抓取日期不是文件编制日期。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-244",
    "expectedSourceRecordIds": [
      244
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          244
        ],
        "mode": "address-reference",
        "use": "八号桥一期创意园；创意产业办公",
        "address": "建国中路8号",
        "note": "现代园区用途明确；旧市政车辆停放设施的存废和单体对应仍未核实。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "bridge8",
            "title": "八号桥运营方：联系地址",
            "url": "https://www.bridge8group.com/index/contact/index.html",
            "informationAsOf": null,
            "accessedOn": "2026-09-24",
            "supports": "运营方联系地址建国中路8号8号楼4楼。"
          },
          {
            "id": "bridge8-use",
            "title": "上海市企业服务云：八号桥空间租赁",
            "url": "https://www.ssme.sh.gov.cn/public/product%21serviceDetail.do?productId=2c91c2876e3f379f016e63a5fbb87d44",
            "informationAsOf": null,
            "accessedOn": "2026-09-24",
            "supports": "八号桥一期地址建国中路8—10号，聚集创意设计公司。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-245",
    "expectedSourceRecordIds": [
      245
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          245
        ],
        "mode": "address-reference",
        "use": "八号桥一期创意园；办公及沿街商业",
        "address": "建国中路10号",
        "note": "超媒体联系地址支持园区办公；不把旧工程处名称当作现用途。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "bridge8-use",
            "title": "上海市企业服务云：八号桥空间租赁",
            "url": "https://www.ssme.sh.gov.cn/public/product%21serviceDetail.do?productId=2c91c2876e3f379f016e63a5fbb87d44",
            "informationAsOf": null,
            "accessedOn": "2026-09-24",
            "supports": "八号桥一期地址建国中路8—10号，聚集创意设计公司。"
          },
          {
            "id": "metamedia",
            "title": "超媒体：联系我们",
            "url": "https://www.metamedia.art/contact",
            "informationAsOf": null,
            "accessedOn": "2026-09-24",
            "supports": "上海联系地址建国中路10号八号桥，支持园区办公用途。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-248",
    "expectedSourceRecordIds": [
      248,
      249
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          248,
          249
        ],
        "mode": "address-reference",
        "use": "中国疾控中心寄生虫病预防控制所；寄生虫病检测／科研机构",
        "address": "瑞金二路207号",
        "note": "官方明确专项检测收样室及机构门址。护士学校和Institut Pasteur是不同历史记录，尚未据此核定两者各自楼栋；不能简写为瑞金医院。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "parasite",
            "title": "中国疾控中心寄生虫病所：咨询检测",
            "url": "https://www.ipd.org.cn/view4171.html",
            "informationAsOf": "2024-10-09",
            "accessedOn": "2026-09-28",
            "supports": "瑞金二路207号设寄生虫病专项检测收样室；页脚为寄生虫病预防控制所同号地址。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-252",
    "expectedSourceRecordIds": [
      252
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          252
        ],
        "mode": "address-reference",
        "use": "Swirl鸡尾酒吧；餐饮娱乐",
        "address": "复兴中路577号",
        "note": "门店经营方给出的现代同号地址；没有证据证明中法联谊会旧建筑仍存或门店占用整个旧址。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "swirl",
            "title": "SG Group：Swirl门店",
            "url": "https://sg-management.jp/establishments/swirl/",
            "informationAsOf": null,
            "accessedOn": "2026-09-28",
            "supports": "运营方列葡萄酒鸡尾酒吧Swirl，上海复兴中路577号。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-259",
    "expectedSourceRecordIds": [
      259
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          259
        ],
        "mode": "address-reference",
        "use": "上海市第四聋校教育设施（31号3楼网络接入点）",
        "address": "皋兰路31号3F；招生联系地址另为香山路28号",
        "note": "2026年官方网络采购仍列31号3F，而招生文件用香山路28号。保留不同功能门址，不声称学校已整体迁出或每栋楼都用于教学，也不证明原国际救济委员会事所与校舍本体相同。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc3-education2026",
            "title": "上海政府采购：2026年黄浦教育城域网服务招标文件，第39页",
            "url": "https://jpg.zfcg.sh.gov.cn/sh-gov-open-doc/1108QZ/13b07c4e-f985-4fb5-bd14-31d9d0731fe5.pdf",
            "informationAsOf": "2026年3月",
            "accessedOn": "2026-09-29",
            "supports": "PDF第39页经文本及整页图像核验：序38第四聋校接入点为皋兰路31号3F，序29重庆南路幼儿园为重庆南路229弄2号。支持学校网络服务地址，不证明独栋边界或招生活动门口。"
          },
          {
            "id": "fc3-admissions2026",
            "title": "上海市政府：2026年黄浦区幼儿园招生入园工作实施意见（特殊教育联系地址）",
            "url": "https://www.shanghai.gov.cn/hpqxqjy/20260420/32fe4193d679456f94194479ba4372a4.html",
            "informationAsOf": "2026-04-15",
            "accessedOn": "2026-09-29",
            "supports": "特殊教育报名联系第四聋校用香山路28号；与网络接入点皋兰路31号3F分列，不误称学校已从31号完全撤离。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-265",
    "expectedSourceRecordIds": [
      265
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          265
        ],
        "mode": "address-reference",
        "use": "上海锦江国际旅游股份有限公司办公",
        "address": "长乐路191号（联系人在A座2楼）",
        "note": "2025年半年度报告第5页明确办公地址；注册地址是延安东路100号，二者已区分。现代旅游企业办公不证明旧圣心小学楼体仍存或用途覆盖整院。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc3-jinjiang",
            "title": "上海锦江国际旅游股份有限公司2025年半年度报告，第5页",
            "url": "https://static.cninfo.com.cn/finalpage/2025-08-30/1224622865.PDF",
            "informationAsOf": "2025年半年度",
            "accessedOn": "2026-09-29",
            "supports": "已核PDF第5页图像：公司办公地址为长乐路191号，证券联系人为A座2楼；注册地址另为延安东路100号27楼。支持办公用途而非仅凭注册推定。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-289",
    "expectedSourceRecordIds": [
      289
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          289
        ],
        "mode": "address-reference",
        "use": "一手·好面专门店，沿街餐饮",
        "address": "长乐路235号",
        "note": "2026年8月区融媒报道精确门址及营业场景，支持当代店铺用途；未证明Church of Christ King原建筑保存、原教堂完整地块与现代235号一致或整栋仅作餐饮。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc3-noodle",
            "title": "上海黄浦（搜狐发布）：谁懂这一口，奶皮子裹着的中式意面",
            "url": "https://m.sohu.com/a/1062364200_121668715",
            "informationAsOf": "2026-08-13",
            "accessedOn": "2026-09-29",
            "supports": "区融媒记者报道一手·好面专门店在长乐路235号营业；支持现代沿街餐饮，不证明历史教堂原物改作面馆。打开正文失败，检索缓存提供记者及完整门址段落。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-316",
    "expectedSourceRecordIds": [
      316
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          316
        ],
        "mode": "address-reference",
        "use": "黄浦区社区学院教育服务点（2026年网络接入清单）",
        "address": "瑞金二路400号",
        "note": "原PDF第39页表序41经图像核实。单位名括注“瑞金南路校区”，地址栏确为“瑞金二路400号”，原样保留差别；只说明现代服务地址，不据此确认开明中学旧楼或办学建制继承。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc4-community2026",
            "title": "上海政府采购：2026年黄浦教育城域网服务招标文件，第39页",
            "url": "https://jpg.zfcg.sh.gov.cn/sh-gov-open-doc/1108QZ/13b07c4e-f985-4fb5-bd14-31d9d0731fe5.pdf",
            "informationAsOf": "2026年3月",
            "accessedOn": "2026-09-29",
            "supports": "PDF第39页整页图像及文本核验：序41上海市黄浦区社区学院（瑞金南路校区）对应地址瑞金二路400号。保留文件的校区名与地址，不擅改路名；证明教育网络接入单位门址，不证明开明中学原楼存续。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-322",
    "expectedSourceRecordIds": [
      322
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          322
        ],
        "mode": "address-reference",
        "use": "卢湾体育场（跑道、足球等体育活动）",
        "address": "建国西路135号",
        "note": "2025年官方开放表与现行高德POI均同号。历史来源英文Power Station与中文无线电台存在语义差异，原字段保留；现代体育场用途不证明旧设施与整场边界一致，也不扩展给133号。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc4-luwan-sports",
            "title": "上海黄浦：2025年五一期间公共体育场馆开放一览表",
            "url": "https://m.thepaper.cn/baijiahao_30753236",
            "informationAsOf": "2025-04-30",
            "accessedOn": "2026-09-29",
            "supports": "官方政务号开放表明确卢湾体育场为建国西路135号，开放跑道和足球项目。区别于肇嘉浜路128号卢湾体育馆；不把2025节假日时间当作常年开放时间。"
          },
          {
            "id": "fc4-luwan-map",
            "title": "高德地图：卢湾体育场",
            "url": "https://www.amap.com/place/B00155GGA6",
            "informationAsOf": null,
            "accessedOn": "2026-09-29",
            "supports": "现行POI同样将卢湾体育场列在建国西路135号，仅辅助核验现代门址，未采纳坐标或面积用于地图修正。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-330",
    "expectedSourceRecordIds": [
      330
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          330
        ],
        "mode": "address-reference",
        "use": "UCCA Kids上海儿童艺术教育、工作坊及活动场所",
        "address": "建国西路262号",
        "note": "运营方现行页面明确上海点门址与课程用途。只确认现代使用，不把历史未具名小学／幼稚园等同UCCA建制，也不假定官网北京主馆开放时间适用于上海。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc4-ucca-kids",
            "title": "UCCA尤伦斯当代艺术中心官网：UCCA Kids",
            "url": "https://ucca.org.cn/kids/",
            "informationAsOf": null,
            "accessedOn": "2026-09-29",
            "supports": "运营方现行页面列上海UCCA Kids地址建国西路262号，提供儿童艺术课程、工作坊和展览活动。页面未标更新日，不把北京主馆开放时间或总机归给上海点。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-333",
    "expectedSourceRecordIds": [
      333,
      334
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          333,
          334
        ],
        "mode": "address-reference",
        "use": "上海市徐汇区向阳小学永嘉校区",
        "address": "永嘉路249号",
        "note": "2025年官方学校表明确该校区门址，学校现行栏目仍列永嘉校区课表并更新至2026年9月。同址历史小学／幼稚园和中国中学女子部两条记录继续分开，未证明旧建筑物理存续或全部沿革。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc4-xiangyang2025",
            "title": "上海市政府：2025年徐汇区小学办学规模等公示表",
            "url": "https://www.shanghai.gov.cn/xhqywjy/20250411/5c18b5ed91324ff48f27a95a654ab73d.html",
            "informationAsOf": "2025年招生公示",
            "accessedOn": "2026-09-29",
            "supports": "公示表第一项向阳小学列永嘉校区于永嘉路249号；另一个向阳校区为襄阳南路388弄15号，不把两门址混用。"
          },
          {
            "id": "fc4-xiangyang-current",
            "title": "向阳小学官网：学校信息公开",
            "url": "https://xyxx.xhedu.sh.cn/cms/app/info/cat/index.php/1923",
            "informationAsOf": null,
            "accessedOn": "2026-09-29",
            "supports": "现行学校信息栏目仍列永嘉校区课表，并有2026年9月陪餐安排；与2025官方门址表交叉支持办学用途，不证明历史中国中学女子部与向阳小学同一建制。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-335",
    "expectedSourceRecordIds": [
      335,
      337
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          335,
          337
        ],
        "mode": "address-reference",
        "use": "襄一幼儿园分部（315—317号校区范围）",
        "address": "襄阳南路315—317号",
        "note": "2025年官方校园保洁采购PDF经整页图像核实，范围明确包含315号。2004年爱群托儿所旧名不沿用作现名称；不推定315与317的逐栋分工，荣园小学与妇女补习学校两条历史记录仍独立。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc4-nursery2025",
            "title": "徐汇区政府采购：公办幼儿园日常保洁服务，徐采中招2025-116",
            "url": "https://sh-gov-open-doc.oss-cn-shanghai.aliyuncs.com/1108QZ/e3d238fe-3b0e-40ae-8af1-5ca2b1e22615.pdf",
            "informationAsOf": "2025年采购文件",
            "accessedOn": "2026-09-29",
            "supports": "PDF第16页（印刷页15）文字与整页图像核验：北片表序8襄一幼儿园（分）地址襄阳南路315—317号。范围包含315，支持该门址组学前教育，不把315、317两栋的具体分工或旧校继承关系写死。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-357",
    "expectedSourceRecordIds": [
      357
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          357
        ],
        "mode": "current-use",
        "use": "上海市少数民族联合会活动点；办公、会议接待及展览展示",
        "address": "新乐路55号",
        "note": "2025年修缮项目用途优先于地图POI的“教堂”标签；不据历史名认定现在仍作宗教礼拜。",
        "identityBasis": "新乐路55号原东正教堂修缮为民族联活动点，有项目沿革；不再标为宗教礼拜。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "xinle",
            "title": "新乐路55号修缮项目：设计方项目介绍",
            "url": "https://www.archina.com/index.php?a=show&g=works&id=158414&m=index",
            "informationAsOf": "2025-04-11",
            "accessedOn": "2026-09-28",
            "supports": "设计院介绍修缮后为上海市少数民族联合会办公、会议接待、展览展示场所。"
          },
          {
            "id": "xinle-official",
            "title": "上海市民族联2024年项目绩效自评",
            "url": "https://www.shanghai.gov.cn/cmsres/ec/ec1ac32cd10a4818b1a1922a7a8a7153/d9e3a43b34b86f9f6d3f9b8efd75447a.pdf",
            "informationAsOf": "2024年度",
            "accessedOn": "2026-09-28",
            "supports": "新乐路55号已完成房屋修缮，并启动民族工作展陈工程；不支持现仍作礼拜场所。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-361",
    "expectedSourceRecordIds": [
      361
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          361
        ],
        "mode": "current-use",
        "use": "上海地产大厦重建地块；裙房1M为言盐西餐厅，原影院建筑已拆",
        "address": "东湖路9号上海地产大厦（裙房1M局部餐饮）",
        "note": "上观明确杜美大戏院→东湖电影院→拆院建楼的沿革，2001年改称地产大厦，2010年影院人员退出。高德门址与2026年餐饮点评支持裙房现用；不把整栋大厦都写为餐厅，不把旧计划中的放映厅当现营影院，也不据同号断言旧建筑留存。",
        "identityBasis": "杜美大戏院→东湖电影院→拆院重建上海地产大厦沿革有据；区分整栋与裙房餐饮。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc4-doumer",
            "title": "上观新闻：小马路上的老上海影剧院沿革",
            "url": "https://www.shobserver.cn/wx/detail.do?id=78699",
            "informationAsOf": "2018-01-31",
            "accessedOn": "2026-09-29",
            "supports": "杜美路9号杜美大戏院后为东湖电影院；报道记1994年转制后拆院重建，2000年大厦竣工、2001年更名地产大厦、2010年影院人员退出。支持原影院并非原建筑保留，不把改建计划中的放映厅当今日电影院。"
          },
          {
            "id": "fc4-stonesal",
            "title": "高德地图：Stonesal言盐西餐厅",
            "url": "https://www.amap.com/place/B0FFIKANHD",
            "informationAsOf": null,
            "accessedOn": "2026-09-29",
            "supports": "POI明确东湖路9号上海地产大厦裙房1M的餐饮／酒吧门店；只限裙房局部，不代表整栋大厦。未使用此POI坐标改地图。"
          },
          {
            "id": "fc4-stonesal-reviews",
            "title": "携程：言盐西餐厅资料与点评",
            "url": "https://you.ctrip.com/food/2/20346189.html",
            "informationAsOf": "页面含2026年1—8月点评",
            "accessedOn": "2026-09-29",
            "supports": "门店资料列东湖路9号上海地产大厦裙房1M，近期用户点评辅助支持餐饮使用；用户内容不是官方营业认证，不采用机器营业时间推断全天开放。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-376",
    "expectedSourceRecordIds": [
      376
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          376
        ],
        "mode": "address-reference",
        "use": "上海艺术研究中心办公、艺术研究与档案相关业务",
        "address": "巨鹿路709号",
        "note": "2026-08-10文旅局机构页明确门址，支持现代事业单位使用。善道堂原建筑存续、是否对外开放均未核，不将单位业务内容全部理解成整楼公众展陈。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc4-art709",
            "title": "上海市文旅局：上海艺术研究中心",
            "url": "https://whlyj.sh.gov.cn/zsdw/20200927/df9ea17db5bb4409a9a6f9b8a9b551fb.html",
            "informationAsOf": "2026-08-10",
            "accessedOn": "2026-09-29",
            "supports": "现行官方机构介绍列巨鹿路709号，支持艺术研究、档案管理等事业单位办公门址；不证明善道堂旧建筑仍存或对公众开放。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-378",
    "expectedSourceRecordIds": [
      378
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          378
        ],
        "mode": "address-reference",
        "use": "蓝宝石公寓居住；一楼局部有版画门店",
        "address": "巨鹿路741号（租赁住宅及一楼南三室）",
        "note": "2026年7月住宅房源与高德底层门店分别支持现代住宅和局部商业，主楼不按门店改成美术馆。广告附带的领事馆历史、年代和文保级别不采信为考证结论，仍未证明原Residential Complex整组边界一致。",
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc4-sapphire-rent",
            "title": "吾原地产：巨鹿路741号蓝宝石公寓出租房源",
            "url": "https://www.wu-yuan.cn/real-estates/RC-4711",
            "informationAsOf": "2026-07-13（房源标注）",
            "accessedOn": "2026-09-29",
            "supports": "经纪机构的带日期实物房源列741号蓝宝石公寓三楼两居室出租，支持现代居住功能。未采用广告附带的建筑年代、领事馆历史或文保等级作为历史考证。"
          },
          {
            "id": "fc4-sapphire-shop",
            "title": "高德地图：MOND时光画廊欧洲古董版画",
            "url": "https://www.amap.com/place/B0L2RAM3GE",
            "informationAsOf": null,
            "accessedOn": "2026-09-29",
            "supports": "POI列巨鹿路741号蓝宝石公寓一楼南三室为版画专营门店，辅助说明底层局部商业；不把整楼写成美术馆。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-381",
    "expectedSourceRecordIds": [
      381
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          381
        ],
        "mode": "address-reference",
        "use": "上海市医院协会综合办公室（201室）",
        "address": "巨鹿路807号201室",
        "note": "现行官网明确此为综合办公室地址2，仅证实具体房间办公使用；不把行业协会误写成仍在营业的济华医院，也不由这一办公室推断整楼用途。",
        "retainedHold": {
          "reason": "已核实际分片research/unresolved-landmarks/010-b.json，按ID定位。建议按现代对应口径改unresolved/no，历史已确认事实单列，勿丢失已查沿革。 执行hold时只撤本研究批准形成的现代用途override/采用结果；保留历史feature、原名、历史沿革、XY及其他经独立批准的来源，不将null写成一条有效override。",
          "reviewRef": "research/corrections/2026-09-18-001-010/README.md"
        },
        "reviewedOn": "2026-09-29",
        "sources": [
          {
            "id": "fc4-association807",
            "title": "上海市医院协会官网：联系我们",
            "url": "https://www.shyyxh.cn/node2/n4/n12/index.html",
            "informationAsOf": null,
            "accessedOn": "2026-09-29",
            "supports": "官方现行联系页列综合办公室地址2为巨鹿路807号201室。只证明该房间的行业协会办公，不说明整楼还是济华医院、医院门诊或展览场所。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-404",
    "expectedSourceRecordIds": [
      404
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          404
        ],
        "mode": "address-reference",
        "use": "上海音乐学院音乐城堡：音乐研究、工作室及文化展示用途",
        "address": "淮海中路1131号",
        "note": "学校2024报道明确同号音乐城堡修缮后设国际音乐节赛研究中心、大师工作室和展览。只核现代门址用途，不证明原上海网球场与现单栋建筑边界相同；1189号美育楼及其乐器博物馆不混入，旧家具公司名录不沿用。",
        "reviewedOn": "2026-09-30",
        "sources": [
          {
            "id": "fc5-music1131",
            "title": "上海音乐学院转载音乐周报：校园开放与历史建筑用途",
            "url": "https://www.shcmusic.edu.cn/_t112/2024/0117/c1686a50160/page.htm",
            "informationAsOf": "2024-01-10（正文发布时间）",
            "accessedOn": "2026-09-30",
            "supports": "正文明确1131号音乐城堡2023年修缮后设国际音乐节赛研究中心、大师工作室及文化展览，2024元旦校园开放；不沿用旧达芬奇家具名录，不把1189号东方乐器博物馆搬到1131号。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-408",
    "expectedSourceRecordIds": [
      408
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          408
        ],
        "mode": "address-reference",
        "use": "复旦大学附属眼耳鼻喉科医院宝庆院区；医疗",
        "address": "宝庆路19号",
        "note": "现代同号医疗用途有地图记录；旧大华医院与现楼栋是否同一建筑另核。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "baoqing",
            "title": "高德：眼耳鼻喉科医院宝庆院区",
            "url": "https://ditu.amap.com/place/B00154DGB4",
            "informationAsOf": null,
            "accessedOn": "2026-09-24",
            "supports": "医院宝庆院区位于宝庆路19号。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-411",
    "expectedSourceRecordIds": [
      411
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          411
        ],
        "mode": "address-reference",
        "use": "上海市第二初级中学；公办初中",
        "address": "永嘉路388号",
        "note": "以2025年办学公示和现学校官网为准，不沿用中国中学旧校址资料当作现学校名称。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "school388",
            "title": "徐汇区2025年初中办学与招生公示",
            "url": "https://www.xuhui.gov.cn/xxgk/portal/article/detail?id=8a4c0c0692292eab0196199c38072478",
            "informationAsOf": "2025年",
            "accessedOn": "2026-09-28",
            "supports": "上海市第二初级中学，公办初中，永嘉路388号。"
          },
          {
            "id": "school388-live",
            "title": "上海市第二初级中学官网",
            "url": "https://www.shiers.cn/cjzx/articleList.aspx?id=12021&typeId=323",
            "informationAsOf": null,
            "accessedOn": "2026-09-28",
            "supports": "官网列2026年校园开放日通知及永嘉路388号联系地址。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-413",
    "expectedSourceRecordIds": [
      413,
      1716
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          413,
          1716
        ],
        "mode": "address-reference",
        "use": "复旦大学附属眼耳鼻喉科医院汾阳院区；医疗",
        "address": "汾阳路83号",
        "note": "院区门址明确；VS413波兰公使馆的先后占用史仍待核，VS1716医院记录也不能直接限定为名录10号楼／水塔或地图9号楼。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "fenyang",
            "title": "中国医药信息查询平台：眼耳鼻喉科医院",
            "url": "https://www.dayi.org.cn/hospital/1118273",
            "informationAsOf": null,
            "accessedOn": "2026-09-28",
            "supports": "复旦大学附属眼耳鼻喉科医院总院区地址汾阳路83号。"
          },
          {
            "id": "fenyang-amap",
            "title": "高德：眼耳鼻喉科医院汾阳院区9号楼",
            "url": "https://www.amap.com/place/B0FFGJSF7U",
            "informationAsOf": null,
            "accessedOn": "2026-09-24",
            "supports": "医院楼栋POI地址汾阳路83号；仅用于核对现代院区，不认定VS地标对应9号楼。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-414",
    "expectedSourceRecordIds": [
      414
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          414
        ],
        "mode": "address-reference",
        "use": "五原幼儿园永嘉园，学前教育",
        "address": "永嘉路420号",
        "note": "2025政府采购第17页（印刷16）北片序23直接列园名和门址，核实图像，支持同号学校现用。旧中西第二小学的办学承接与具体旧楼存续未在本轮核定，未与该园其他校区混用。",
        "reviewedOn": "2026-09-30",
        "sources": [
          {
            "id": "fc5-nursery420",
            "title": "徐汇政府采购：公办幼儿园日常保洁服务，2025-116，第17页",
            "url": "https://sh-gov-open-doc.oss-cn-shanghai.aliyuncs.com/1108QZ/e3d238fe-3b0e-40ae-8af1-5ca2b1e22615.pdf",
            "informationAsOf": "2025年7月",
            "accessedOn": "2026-09-30",
            "supports": "本轮核对PDF第17页（印刷16）整页图像和文字：北片序23五原幼儿园（永嘉园）为永嘉路420号；与同园武康园400号分列，支持现代学前教育门址。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-416",
    "expectedSourceRecordIds": [
      416
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          416
        ],
        "mode": "address-reference",
        "use": "上海市徐汇区向阳小学（教育）",
        "address": "襄阳南路388弄15号",
        "note": "学校官网与2025区政府抽检地址相互支持该精确现代门址办学。旧388-15按弄号解释可查到，但法国兵营与现校舍的原楼／院落范围及拆建另待核，不改历史分类。",
        "reviewedOn": "2026-09-30",
        "sources": [
          {
            "id": "fc7-xiangyang-school",
            "title": "上海市徐汇区向阳小学：校园动态／学校地址",
            "url": "https://xyxx.xhedu.sh.cn/cms/app/info/cat/index.php/2572",
            "informationAsOf": null,
            "accessedOn": "2026-09-30",
            "supports": "学校官网检索结果列襄阳南路388弄15号；原页复取只得栏目壳，地址与2025区政府抽检明细交叉核对。"
          },
          {
            "id": "fc7-xiangyang-school2025",
            "title": "徐汇区市场监管局：2025年学生服监督抽检明细",
            "url": "https://www.xuhui.gov.cn/xxgk/portal/article/detail?id=8a4c0c069a97abda019ca35e912a144e",
            "informationAsOf": "2025年抽检",
            "accessedOn": "2026-09-30",
            "supports": "政府表第12—13项列向阳小学教室、襄阳南路388弄15号；支持教育用途，不证明法国兵营建筑原物存续。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-417",
    "expectedSourceRecordIds": [
      417
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          417
        ],
        "mode": "address-reference",
        "use": "上海中国画院美术馆；展览",
        "address": "岳阳路197号",
        "note": "仅确认同号现代美术馆。1937年治疗院迁址资料涉及旧45号等门牌变化，未据同号断言圣心医院原楼仍在。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "art-museum",
            "title": "上海市文旅局：2025年美术馆名录",
            "url": "https://whlyj.sh.gov.cn/msg/20250928/db0cbc0a1edf478f99c4900522a56e3b.html",
            "informationAsOf": "2025-09-28",
            "accessedOn": "2026-09-28",
            "supports": "上海中国画院美术馆列于徐汇区岳阳路197号。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-418",
    "expectedSourceRecordIds": [
      418
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          418
        ],
        "mode": "current-use",
        "use": "建国公寓；公寓住宅",
        "address": "建国西路394号",
        "note": "资料将现代建国公寓与旧道斐南／法国太子公寓关联；本轮保留二级来源，不修坐标。",
        "identityBasis": "道斐南／法国太子公寓与建国公寓名称、门址对应；保留百科二级来源及未标资料日期限制。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "jianguo",
            "title": "维基百科：建国公寓",
            "url": "https://zh.wikipedia.org/wiki/建国公寓",
            "informationAsOf": null,
            "accessedOn": "2026-09-28",
            "supports": "建国西路394号为高层公寓住宅，旧称法国太子公寓／道斐南公寓。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-422",
    "expectedSourceRecordIds": [
      422
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          422
        ],
        "mode": "address-reference",
        "use": "中国科学院上海分院等机构所在院落；科研与办公",
        "address": "岳阳路319号",
        "note": "院落地址已证，不能据此把French China Field Battalion整条记录定位为院内11号楼法国领事住宅。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "cas",
            "title": "中国科学院上海分院：信息公开联系方式",
            "url": "https://shb.cas.cn/xxgk2016/xxgklxfs2016/",
            "informationAsOf": null,
            "accessedOn": "2026-09-28",
            "supports": "上海分院综合办公室通信地址岳阳路319号；只支持院落层面机构办公。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-440",
    "expectedSourceRecordIds": [
      440
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          440
        ],
        "mode": "address-reference",
        "use": "上海歌剧院办公及艺术机构使用",
        "address": "常熟路100弄10号",
        "note": "2026官方招聘地点和高德门址相合；只确认现代艺术机构办公，不将高德剧场标签解释为整栋对外剧场，也不据同号确认苏俄领事馆原楼保存。",
        "reviewedOn": "2026-09-30",
        "sources": [
          {
            "id": "fc7-opera2026",
            "title": "上海市人社局：上海歌剧院2025年第四季度第二批招聘公告",
            "url": "https://rsj.sh.gov.cn/tzpgg_17408/20260104/t0035_1437735.html",
            "informationAsOf": "2026-01-04",
            "accessedOn": "2026-09-30",
            "supports": "官方检索正文列常熟路100弄10号人力资源部；原页复取失败。支持歌剧院办公地址，不将高德剧场分类解释为整楼对外演出空间。"
          },
          {
            "id": "fc7-opera-amap",
            "title": "高德地图：上海歌剧院",
            "url": "https://www.amap.com/place/B00154AF39",
            "informationAsOf": null,
            "accessedOn": "2026-09-30",
            "supports": "公开检索POI列常熟路100弄10号，原页复取失败；仅辅助核对地址，类型标签不足界定实际演出场地。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-463",
    "expectedSourceRecordIds": [
      463
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          463
        ],
        "mode": "address-reference",
        "use": "美豪丽致酒店上海徐家汇衡山路店，酒店住宿及配套餐饮",
        "address": "建国西路691号",
        "note": "携程现行酒店正文与高德门址一致，支持现代同号住宿用途。不采用同号写字楼广告的矛盾面积，也未证实原法国兵营单体何时拆建、酒店是否覆盖全营区。",
        "reviewedOn": "2026-09-30",
        "sources": [
          {
            "id": "fc5-jg691-map",
            "title": "高德地图：美豪丽致酒店上海徐家汇衡山路店",
            "url": "https://www.amap.com/place/B0FFJQNQLN",
            "informationAsOf": null,
            "accessedOn": "2026-09-30",
            "supports": "现行酒店POI明列上海徐汇建国西路691号，辅助核现代住宿用途，不采用其点位改地图。"
          },
          {
            "id": "fc5-jg691-hotel",
            "title": "携程：美豪丽致酒店上海徐家汇衡山路店",
            "url": "https://hotels.ctrip.com/hotels/479628.html",
            "informationAsOf": null,
            "accessedOn": "2026-09-30",
            "supports": "现行酒店正文明确建国西路691号、住宿及餐饮设施，与高德门址一致。排除名称同号写字楼广告中总面积与可租面积矛盾的数据，不据酒店开业时间断定兵营拆建时间。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-464",
    "expectedSourceRecordIds": [
      464
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          464
        ],
        "mode": "address-reference",
        "use": "天平街道综合执法队办公服务点（237—241号范围）",
        "address": "宛平路237—241号",
        "note": "2026年3月政府采购PDF第17页将237—241和295号共同列为执法队服务门址。可以支持241所在范围的公共机构用途，但不能把295号的楼层、人员或两处合计面积转给241号；燕平会馆与今楼物理对应尚未核。",
        "reviewedOn": "2026-09-30",
        "sources": [
          {
            "id": "fc5-wp241",
            "title": "徐汇政府采购：天平街道本部及周边延伸物业管理，2026-027",
            "url": "https://jpg.zfcg.sh.gov.cn/sh-gov-open-doc/1108QZ/bd4ff1d5-bfd0-46f5-94ee-90b21786dbf0.pdf",
            "informationAsOf": "2026年3月",
            "accessedOn": "2026-09-30",
            "supports": "PDF第17页第三部分和表1-1整页核验：综合执法队服务地址含宛平路295号、237—241号。只证明237—241范围的机关用途，不把295号楼层布局或合计面积赋给241号。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-479",
    "expectedSourceRecordIds": [
      479,
      480
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          479,
          480
        ],
        "mode": "address-reference",
        "use": "兴国宾馆院区；酒店服务",
        "address": "兴国路72号",
        "note": "VS479运动场只确认同号院区，不认作1号楼；VS480 Hazelwood沿革有1号楼线索，但军营分类与官方住宅历史有冲突。",
        "retainedHold": {
          "reason": "已核实际分片research/unresolved-landmarks/008-a.json，按ID定位。单独核球场原点、范围及现功能；未核前hold整组或只对480受限展示，不把479标原酒店楼。 执行hold时只撤本研究批准形成的现代用途override/采用结果；保留历史feature、原名、历史沿革、XY及其他经独立批准的来源，不将null写成一条有效override。 同址组成员：479,480；root须逐成员追踪独立证据，不能据本patch改写组外研究或抹去其他批准。",
          "reviewRef": "research/corrections/2026-09-18-001-010/README.md"
        },
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "xingguo",
            "title": "长宁区2026年度安全生产检查名单",
            "url": "https://zwgk.shcn.gov.cn/xxgk/yjgl-zw/2026/191/81896.html",
            "informationAsOf": "2026年度",
            "accessedOn": "2026-09-24",
            "supports": "名单列上海兴国宾馆有限公司，兴国路72号。"
          },
          {
            "id": "xingguo-history",
            "title": "长宁区规划资源局：兴国宾馆",
            "url": "https://www.shcn.gov.cn/col7698/20230119/1229080.html",
            "informationAsOf": "2023-01-19",
            "accessedOn": "2026-09-24",
            "supports": "1号楼位于72号大院内，1935年建，原太古洋行大班住宅；与VS军营用途记载存在差别。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-1237",
    "expectedSourceRecordIds": [
      1237
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          1237
        ],
        "mode": "current-use",
        "use": "外滩信号台：一楼旅游咨询、文创及历史展示，二楼咖啡茶点（2026年9月报道）",
        "address": "中山东二路1号甲",
        "note": "近期报道足以支持分层现代用途；9月5日报道的二层餐饮是计划，9月23日实访才称已提供咖啡茶点、三楼未开放。另有1993年平移历史，今点位不能当旧路口未变，不在本轮改坐标。",
        "identityBasis": "Gutzlaff信号台名称与今外滩信号台对应；说明1993年平移，不把今日用途附会为原点未变。",
        "reviewedOn": "2026-09-30",
        "sources": [
          {
            "id": "fc7-signal2026",
            "title": "新民晚报（新浪转载）：百年外滩信号台开放",
            "url": "https://finance.sina.com.cn/jjxw/2026-09-05/doc-iniquccw0451976.shtml",
            "informationAsOf": "2026-09-05",
            "accessedOn": "2026-09-30",
            "supports": "已读正文，底层旅游咨询与历史图文展示已开放；二层餐饮在本篇中仍为后续计划，不按该篇当已开。"
          },
          {
            "id": "fc7-signal-september",
            "title": "侬好上海：外滩百年信号台试运营开放",
            "url": "https://www.sohu.com/a/1079914166_121325802",
            "informationAsOf": "2026-09-23",
            "accessedOn": "2026-09-30",
            "supports": "新闻账号实访检索正文列中山东二路1号甲、一楼旅游咨询／文创／外滩历史陈列，二楼咖啡茶点、三楼暂未开放。检索收录正文可读，原页复取受限；支持近期分层用途，不推断全天免费进入各层。"
          },
          {
            "id": "fc7-signal-history",
            "title": "维基百科：Gutzlaff Signal Tower",
            "url": "https://en.wikipedia.org/wiki/Gutzlaff_Signal_Tower",
            "informationAsOf": null,
            "accessedOn": "2026-09-30",
            "supports": "信号台名称对应及1993年平移历史线索；不能把今日位置当作历史路口点不变，不在本轮更改坐标。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-1239",
    "expectedSourceRecordIds": [
      1239,
      1745
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          1239,
          1745
        ],
        "mode": "address-reference",
        "use": "金陵大楼：至少含住宅用途，2026年有优秀历史建筑住宅修缮采购",
        "address": "四川南路29号",
        "note": "2026官方采购检索正文明确同号金陵大楼及住宅修缮，正文复取受限，高德同号楼名辅助吻合但粗分类为商务楼。因此不写纯住宅或纯办公，不把公告写成已修缮完成。VS1239新华日报条目与1745 YORK HOUSE共享查询证据仍分行，建筑身份、报社所在楼层及旧今边界未在此确认。",
        "reviewedOn": "2026-09-30",
        "sources": [
          {
            "id": "fc5-jinling2026",
            "title": "中国政府采购网：四川南路29号金陵大楼优秀历史建筑住宅修缮公告",
            "url": "https://www.ccgp.gov.cn/cggg/dfgg/jzxcs/202609/t20260918_27354601.htm",
            "informationAsOf": "2026-09-18",
            "accessedOn": "2026-09-30",
            "supports": "官方检索正文标题和采购单位明确四川南路29号金陵大楼优秀历史建筑住宅修缮，采购人为黄浦区房管局；正文复取受限。支持现代楼名和住宅属性，不把采购公告当作已施工或完工，也不证明整栋纯住宅。"
          },
          {
            "id": "fc5-jinling-map",
            "title": "高德地图：金陵大楼",
            "url": "https://ditu.amap.com/place/B001515394",
            "informationAsOf": null,
            "accessedOn": "2026-09-30",
            "supports": "现行POI列金陵大楼于四川南路29号，平台粗分类商务写字楼；与住宅修缮公告并存，不能只凭POI类别排除住宅或认定整栋纯办公。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-1742",
    "expectedSourceRecordIds": [
      1742
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          1742
        ],
        "mode": "current-use",
        "use": "安康公寓，居民住宅（2025年修缮报道）",
        "address": "乌鲁木齐南路176号",
        "note": "上海徐汇2025报道确认同号安康公寓原名巨福公寓，记居民需求及公共部位修缮；与DUFOUR名称、路名有对应线索。足以记录现代门址居住用途，但尚未逐栋核对VS历史几何，不额外推定底层商户或自动关联名录。",
        "identityBasis": "官方修缮报道将安康公寓与巨福公寓关联，同号居住使用有据；未逐栋核几何。",
        "reviewedOn": "2026-09-30",
        "sources": [
          {
            "id": "fc6-ankang-repair",
            "title": "上海徐汇：我在徐汇修房子，安康公寓内外兼修焕新颜",
            "url": "https://www.thepaper.cn/newsDetail_forward_30111814",
            "informationAsOf": "2025-02-08",
            "accessedOn": "2026-09-30",
            "supports": "官方账号正文确认乌鲁木齐南路176号安康公寓原名巨福公寓，并记居民居住及屋面、外墙、公共部位修缮；支持住宅用途，不据此指定整楼底层商户。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-1749",
    "expectedSourceRecordIds": [
      1749
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          1749
        ],
        "mode": "current-use",
        "use": "淮海大楼；居民住宅兼底层商铺",
        "address": "淮海中路1326号",
        "note": "现名称、住宅使用及Empire Mansions旧称可对应；不采信房产营销页面错误或不一致的建成年份。",
        "identityBasis": "Empire Mansions与淮海大楼沿革相合；分开住宅与底层商铺，保留来源日期。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "huaihai",
            "title": "维基百科：淮海大楼",
            "url": "https://zh.wikipedia.org/wiki/淮海大楼",
            "informationAsOf": null,
            "accessedOn": "2026-09-28",
            "supports": "淮海中路1326号恩派亚公寓，现底层商铺、二层以上居民住宅。"
          },
          {
            "id": "huaihai-residents",
            "title": "澎湃：淮海大楼修缮与居民",
            "url": "https://m.thepaper.cn/newsDetail_forward_11946340",
            "informationAsOf": "2021年",
            "accessedOn": "2026-09-28",
            "supports": "修缮报道明确有长期居住居民，支持住宅而非仅按历史建筑名称猜测用途。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-1758",
    "expectedSourceRecordIds": [
      1758
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          1758
        ],
        "mode": "current-use",
        "use": "瑞金公寓，居民住宅（2025年修缮）；底层具体商户未核",
        "address": "瑞金一路150号",
        "note": "永业集团2025修缮报道将瑞金公寓原名记作爱司公寓并描述居民生活，高德住宅POI给150号；Commons照片补充Estrella／爱司英文名线索。支持现代住宅用途，不把原带店面设计解释为全楼商业，未改既有历史记录、点位或名录关联。",
        "identityBasis": "瑞金／爱司公寓及Estrella旧名可对应，有2025居民住宅修缮来源。",
        "reviewedOn": "2026-09-30",
        "sources": [
          {
            "id": "fc6-ruijin-repair",
            "title": "永业集团：瑞金公寓修缮重生 邬达克名作再续风华",
            "url": "https://www.yongye.com.cn/yongye/zx_jtxw.jsp?artid=55741&colid=280&nian=2025",
            "informationAsOf": "2025-09-04",
            "accessedOn": "2026-09-30",
            "supports": "检索正文可读，记原爱司公寓、2025年修缮及居民日常生活；原页复取超时／受限。与高德150号住宅点交叉支持瑞金公寓居住用途，不把历史带店面设计当作现商户清单。"
          },
          {
            "id": "fc6-ruijin-map",
            "title": "高德地图：瑞金公寓",
            "url": "https://www.amap.com/place/B00155I7V9",
            "informationAsOf": null,
            "accessedOn": "2026-09-30",
            "supports": "可读POI列瑞金一路150号、住宅小区；不采用用户评价作建筑师证据，未提取坐标回写地图。"
          },
          {
            "id": "fc6-estrella-photo",
            "title": "Wikimedia Commons：Estrella Apartments照片说明",
            "url": "https://commons.wikimedia.org/wiki/File%3AEstrella_Apartments.jpg",
            "informationAsOf": "2014-10-29（上传日，不等于拍摄日）",
            "accessedOn": "2026-09-30",
            "supports": "自摄图文件名为Estrella Apartments，说明为爱司公寓／瑞金大楼／瑞金一路150号，补充英文与现代名称线索；本身不是现用途证据。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-1779",
    "expectedSourceRecordIds": [
      1779
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          1779
        ],
        "mode": "address-reference",
        "use": "泰山公寓；居民住宅（622弄内）",
        "address": "淮海中路622弄",
        "note": "来源具体到“弄”，按同号院落候选记录，不能外推到弄内每栋；VS中文金科小学与英文TAI SHAN COURT的字段冲突保留。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "taishan",
            "title": "上观新闻：百年小区越来越嗲",
            "url": "https://sghexport.shobserver.com/html/toutiao/2022/08/22/832385.html",
            "informationAsOf": "2022-08-22",
            "accessedOn": "2026-09-24",
            "supports": "淮海中路622弄的泰山公寓现住居民，弄堂深处有上海社科院；不能以社科院用途代替整组公寓。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-1784",
    "expectedSourceRecordIds": [
      1784
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          1784
        ],
        "mode": "address-reference",
        "use": "JULU 758商业休闲园区",
        "address": "巨鹿路758号",
        "note": "2026静安官方路线和高德商场POI支持同号现址商业用途。官方说明现园区活化自1960年厂房，不能据此称民国Credit Foncier／义品放款银行建筑原样保留，也不能确定旧机构占地与今园区全范围一致。",
        "reviewedOn": "2026-09-30",
        "sources": [
          {
            "id": "fc6-julu758-citywalk",
            "title": "静安区政府：百年洋房，潮流弄堂，戏咖漫游路线",
            "url": "https://www.jingan.gov.cn/jagl/006012/006012004/20260423/c2f25bc4-6ce0-42d9-b777-e2c338d67c10.html",
            "informationAsOf": "2026-04-23",
            "accessedOn": "2026-09-30",
            "supports": "前次可读正文No.3列JULU 758、巨鹿路758号，记1960年上海仪电厂旧空间改作商业；后续复取失败。只支持同号现园区，不证明民国义品放款银行建筑保留或与1960年厂房同体。"
          },
          {
            "id": "fc6-julu758-map",
            "title": "高德地图：JULU758",
            "url": "https://www.amap.com/place/B0FFJZIY0R",
            "informationAsOf": null,
            "accessedOn": "2026-09-30",
            "supports": "检索POI列巨鹿路758号及商场类别，与2026官方商业活化文章交叉核验；不采纳评价代表所有商户，也不改写点位。"
          }
        ]
      }
    ]
  },
  {
    "featureId": "landmark-vs-site-4154",
    "expectedSourceRecordIds": [
      4154
    ],
    "evidence": [
      {
        "sourceRecordIds": [
          4154
        ],
        "mode": "address-reference",
        "use": "复旦大学附属眼耳鼻喉科医院宝庆院区；医疗",
        "address": "宝庆路19号",
        "note": "现代同号医疗用途有地图记录；旧大华医院与现楼栋是否同一建筑另核。",
        "reviewedOn": "2026-09-28",
        "sources": [
          {
            "id": "baoqing",
            "title": "高德：眼耳鼻喉科医院宝庆院区",
            "url": "https://ditu.amap.com/place/B00154DGB4",
            "informationAsOf": null,
            "accessedOn": "2026-09-24",
            "supports": "医院宝庆院区位于宝庆路19号。"
          }
        ]
      }
    ]
  }
]
